{{- $projects := .Values.projects }}
{{- range $project := $projects }}
{{- range $namespace := $project.namespaces }}
{{- range $deployment := $namespace.deployments }}
{{- if $deployment.persistentStorage }}
# TODO: fix for using block storage (no PV needed)
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $deployment.persistentStorage.name }}-volume
  labels:
    type: local
    app: {{ $deployment.appName }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ $deployment.persistentStorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $deployment.persistentStorage.mountPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $deployment.persistentStorage.name }}-claim
  namespace: {{ $namespace.name }}
  labels:
    app: {{ $deployment.persistentStorage.appName }}
spec:
  {{- if $deployment.persistentStorage.storageClassName }}
  storageClassName: {{ $deployment.persistentStorage.storageClassName }}
  {{- else }}
  storageClassName: manual
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $deployment.persistentStorage.size }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
