{{- $projects := .Values.projects }}
{{- range $project := $projects }}
{{- range $namespace := $project.namespaces }}
{{- if $namespace.database }}
{{- if $namespace.database.deploy }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ $namespace.name }}
  labels:
    app: {{ $namespace.database.name }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $namespace.name }}-{{ $namespace.database.name }}-postgres-pv-volume
  labels:
    type: local
    app: {{ $namespace.database.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ $namespace.database.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $namespace.database.name }}-postgres-pv-claim
  namespace: {{ $namespace.name }}
  labels:
    app: {{ $namespace.database.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $namespace.database.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $namespace.database.name }}
  namespace: {{ $namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $namespace.database.name }}
  template:
    metadata:
      labels:
        app: {{ $namespace.database.name }}
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ $namespace.database.name }}-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace.database.name }}
  namespace: {{ $namespace.name }}
  labels:
    app: {{ $namespace.database.name }}
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: {{ $namespace.database.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
