{{- $projects := .Values.projects }}
{{- range $project := $projects }}
{{- range $namespace := $project.namespaces }}
{{- range $deployment := $namespace.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.appName }}
  namespace: {{ $namespace.name }}
spec:
  selector:
    app: {{ $deployment.appName }}
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
{{- end }}
{{- end }}
{{- end }}
