{{- $projects := .Values.projects }}
{{- range $project := $projects }}
{{- range $namespace := $project.namespaces }}
{{- range $deployment := $namespace.deployments }}
{{- if $deployment.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.appName }}
  namespace: {{ $namespace.name }}
spec:
  selector:
    app: {{ $deployment.appName }}
  type: ClusterIP
  ports:
  - port: 80
    {{- if $deployment.service.targetport }}
    targetPort: {{ $deployment.service.targetport }}
    {{- else }}
    targetPort: 80
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
