apiVersion: v1
name: generic-apps-jenkins
home: https://jenkins.io/
version: 0.0.7
description: Open source continuous integration server. It supports multiple SCM tools
  including CVS, Subversion and Git. It can execute Apache Ant and Apache Maven-based
  projects as well as arbitrary scripts.
