# This template contains hardcoded test values
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-whuppl-ops
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - jenkins.k8s.whuppl.io
    secretName: jenkins.k8s.whuppl.io-tls
  rules:
  - host: jenkins.k8s.whuppl.io
    http:
      paths:
      - backend:
          serviceName: jenkins-whuppl
          servicePort: 8080
